const EXACT: Record<string, string> = {
  'already bankrupt': 'Ya estás en bancarrota.',
  'already mortgaged': 'Ya está hipotecada.',
  'already owned': 'Esa propiedad ya tiene dueño.',
  'amount exceeds the loan': 'La cantidad supera el préstamo.',
  'at least two players are needed': 'Hacen falta al menos dos jugadores.',
  'auction not found': 'Esa subasta ya no existe.',
  'bankrupt players cannot bid': 'Los jugadores en bancarrota no pueden pujar.',
  'bid must beat the highest bid': 'La puja debe superar la más alta.',
  'build evenly across the group': 'Construye de forma pareja en todo el grupo.',
  'buying owned properties is disabled': 'Comprar propiedades ajenas está desactivado.',
  'cannot build on a mortgaged property': 'No puedes construir en una propiedad hipotecada.',
  'cannot trade with yourself': 'No puedes negociar contigo mismo.',
  'color must be a hex value like #ff5f6d': 'El color no es válido.',
  'competitive games cannot be joined once started': 'Esta partida competitiva ya empezó y no admite nuevos jugadores.',
  'finish the auction first': 'Primero termina la subasta.',
  'invalid amount': 'Cantidad no válida.',
  'invalid cash amount': 'Cantidad de dinero no válida.',
  'it is not your turn': 'No es tu turno.',
  'lift all mortgages in the group first': 'Levanta antes todas las hipotecas del grupo.',
  'loans are disabled': 'Los préstamos están desactivados.',
  'mortgages are disabled': 'Las hipotecas están desactivadas.',
  'name is required': 'Escribe un nombre.',
  'no jail-free card': 'No tienes carta para salir de la cárcel.',
  'not enough cash': 'No tienes dinero suficiente.',
  'not enough cash to build': 'No tienes dinero suficiente para construir.',
  'not enough jail cards': 'No tienes tantas cartas de salida.',
  'not mortgaged': 'Esa propiedad no está hipotecada.',
  'nothing to buy': 'No hay nada que comprar.',
  'nothing to decline': 'No hay nada que rechazar.',
  'nothing to sell': 'No hay nada que vender.',
  'only properties can hold buildings': 'Solo las propiedades admiten construcciones.',
  'only the host can change rules': 'Solo el anfitrión puede cambiar las reglas.',
  'only the host can hand over hosting': 'Solo el anfitrión puede ceder la anfitrionía.',
  'only the host can remove players': 'Solo el anfitrión puede expulsar jugadores.',
  'only the host can force a move': 'Solo el anfitrión puede forzar una jugada.',
  'that player has nothing to play right now': 'Ese jugador no tiene nada que jugar ahora mismo.',
  'that player is not in the game': 'Ese jugador no está en la partida.',
  'only the host can seat spectators': 'Solo el anfitrión puede sentar espectadores.',
  'only the host can start': 'Solo el anfitrión puede empezar la partida.',
  'only the proposer can cancel': 'Solo quien propuso puede cancelar.',
  'only the recipient can accept': 'Solo el destinatario puede aceptar.',
  'only the recipient can decline': 'Solo el destinatario puede rechazar.',
  'only unimproved, unmortgaged tiles can be bought': 'Solo se pueden comprar propiedades sin construcciones ni hipoteca.',
  'player auctions are disabled': 'Las subastas entre jugadores están desactivadas.',
  'player id already taken': 'Ese jugador ya existe.',
  'roll first': 'Primero tira los dados.',
  'rules are locked once the game starts': 'Las reglas quedaron fijadas al empezar la partida.',
  'sell buildings before trading a property': 'Vende las construcciones antes de intercambiar la propiedad.',
  'sell evenly across the group': 'Vende de forma pareja en todo el grupo.',
  'sell the buildings first': 'Vende primero las construcciones.',
  'sell the buildings in this group first': 'Vende primero las construcciones de este grupo.',
  'settle your debt (or declare bankruptcy) first': 'Salda tu deuda o declárate en bancarrota antes de seguir.',
  'that color is already taken': 'Ese color ya está elegido.',
  'that piece is already taken': 'Esa ficha ya está elegida.',
  'that player is already out': 'Ese jugador ya está fuera.',
  'that player is already seated': 'Ese jugador ya está en la mesa.',
  'that player is not seated': 'Ese jugador no está en la mesa.',
  'that player is out of the game': 'Ese jugador está fuera de la partida.',
  'the game already started': 'La partida ya empezó.',
  'the game is not in progress': 'La partida no está en curso.',
  'the game is over': 'La partida ha terminado.',
  'the highest bidder cannot pass': 'La puja más alta no puede pasar.',
  'the seller cannot bid': 'El vendedor no puede pujar.',
  'the seller cannot pass': 'El vendedor no puede pasar.',
  'the table is full': 'La mesa está llena.',
  'this group cannot be built on': 'En este grupo no se puede construir.',
  'this property is fully built': 'Esta propiedad ya está construida al máximo.',
  'hotel upgrades need hotels on all your groups': 'Para añadir pisos necesitas hotel en todas tus propiedades.',
  'this tile is not owned by another player': 'Esa casilla no pertenece a otro jugador.',
  'tile is being auctioned': 'Esa casilla está en subasta.',
  'trade not found': 'Ese intercambio ya no existe.',
  'trading is disabled': 'Los intercambios están desactivados.',
  'you already passed': 'Ya pasaste en esta subasta.',
  'you already rolled': 'Ya tiraste los dados.',
  'you are already the host': 'Ya eres el anfitrión.',
  'you are out of the game': 'Estás fuera de la partida.',
  'you can only declare bankruptcy while in debt': 'Solo puedes declararte en bancarrota si tienes deudas.',
  'you can only pay before rolling': 'Solo puedes pagar antes de tirar.',
  'you can only use the card before rolling': 'Solo puedes usar la carta antes de tirar.',
  'you cannot afford that bid': 'No puedes pagar esa puja.',
  'you do not own this property': 'Esta propiedad no es tuya.',
  'you do not own this tile': 'Esta casilla no es tuya.',
  'you need the whole group to build': 'Necesitas el grupo completo para construir.',
  'your hourglass is still running': 'Tu reloj de arena aún no se ha vaciado.',
  'missing or invalid player secret': 'Tu sesión de jugador no es válida. Vuelve a entrar en la sala.',
  'spectators cannot play': 'Los espectadores no pueden jugar.',
  'unexpected error': 'Ocurrió un error inesperado.',
};

const PATTERNS: Array<[RegExp, (m: RegExpMatchArray) => string]> = [
  [/^(.+) cannot afford (\d+)$/, (m) => `${m[1]} no puede pagar ${m[2]}.`],
  [/^(.+) cannot cover (\d+)$/, (m) => `${m[1]} no puede cubrir ${m[2]}.`],
  [/^(.+) does not own (.+)$/, (m) => `${m[1]} no es dueño de esa propiedad.`],
  [/^(.+) is out of the game$/, (m) => `${m[1]} está fuera de la partida.`],
  [/^minimum bid is (\d+)$/, (m) => `La puja mínima es ${m[1]}.`],
  [/^the bank lends at most (\d+)$/, (m) => `El banco presta como máximo ${m[1]}.`],
  [/^maxPlayers must be between (\d+) and (\d+)$/, (m) => `El máximo de jugadores debe estar entre ${m[1]} y ${m[2]}.`],
  [/^unknown (tile|deck|card|player|rule|command)/, () => 'Elemento desconocido.'],
  [/^invalid value for/, () => 'Valor no válido.'],
  [/^game .+ not found$/, () => 'Esa sala no existe.'],
  [/^board .+ not found$/, () => 'Ese tablero no existe.'],
];

export function translateError(message: string): string {
  const exact = EXACT[message];
  if (exact) return exact;
  for (const [pattern, render] of PATTERNS) {
    const match = message.match(pattern);
    if (match) return render(match);
  }
  return message;
}
